#pragma once

enum class UiResEnum
{
	MAINMENU_BUTTON_DEFAULT,
	GAMESCENE_BUTTON_BACKPACK,
	GUI_INDICATORLINE,
	GUI_ITEMLIST,
	GUI_ITEMLIST_BUTTON_UPLIST,
	GUI_ITEMLIST_BUTTON_DOWNLIST,
	GUI_ACTIONPANEL_CANVAS,
	GUI_ACTIONPANEL_BUTTON_INFO,
	GUI_ACTIONPANEL_BUTTON_USE,
	GUI_ACTIONPANEL_BUTTON_EAT,
	GUI_ITEMSLISTITEM_CANVAS,
	GUI_SLIDER,
	RES_AMOUNT
};
